"""Prepare the lesson's Mandarin clips (build-time only).
Requires edge-tts==7.2.8; run from the repository root.
Only public lesson text is sent to the speech service. The website reads local MP3s.
"""
import asyncio
import hashlib
import json
from pathlib import Path
import re

import edge_tts

VOICE = 'zh-CN-XiaoxiaoNeural'
ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / 'public' / 'audio'

async def main():
    lesson_files = sorted((ROOT / 'src' / 'lessons').glob('lesson-*.ts'))
    if not lesson_files:
        raise RuntimeError('No lesson files found in src/lessons/.')
    text = '\n'.join(path.read_text() for path in lesson_files)
    phrases = list(dict.fromkeys(re.findall(r'(?:hanzi|chinese):\s*"([^"\n]+)"', text)))
    OUTPUT.mkdir(exist_ok=True)
    manifest = {phrase: hashlib.sha256(phrase.encode()).hexdigest()[:16] + '.mp3' for phrase in phrases}
    limit = asyncio.Semaphore(3)
    async def generate(phrase, filename):
        async with limit:
            destination = OUTPUT / filename
            if destination.exists() and destination.stat().st_size > 1000:
                return
            for attempt in range(3):
                try:
                    # A sentence boundary prevents an isolated word being joined to another clip.
                    spoken = phrase if phrase[-1] in '。！？!?；;' else phrase + '。'
                    temporary = destination.with_suffix('.part')
                    await asyncio.wait_for(edge_tts.Communicate(spoken, VOICE).save(str(temporary)), timeout=45)
                    if temporary.stat().st_size < 1000:
                        raise RuntimeError('Empty audio')
                    temporary.replace(destination)
                    print(f'Generated: {phrase}', flush=True)
                    return
                except Exception:
                    if attempt == 2:
                        raise
                    await asyncio.sleep(1 + attempt)
    await asyncio.gather(*(generate(phrase, filename) for phrase, filename in manifest.items()))
    (ROOT / 'src' / 'audio-manifest.ts').write_text('// Generated by scripts/generate-audio.py.\nexport const audioFiles: Record<string, string> = ' + json.dumps(manifest, ensure_ascii=False, indent=2) + ';\n')
    (OUTPUT / 'sources.json').write_text(json.dumps({'voice': VOICE, 'engine': 'Microsoft Edge online neural TTS', 'generator': 'edge-tts 7.2.8', 'clips': manifest}, ensure_ascii=False, indent=2) + '\n')
    print(f'{len(manifest)} local Mandarin clips ready.', flush=True)

asyncio.run(main())
